# Generated by Django 5.2.13 on 2026-04-11 16:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('experiments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParticipantSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('last_step', models.CharField(choices=[('consent', 'Consent'), ('instructions', 'Instructions'), ('stimuli', 'Listening to stimuli'), ('demographics', 'Demographic questions'), ('done', 'Completed')], default='consent', max_length=16)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('consented_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('abandoned_at', models.DateTimeField(blank=True, null=True)),
                ('device_type', models.CharField(blank=True, max_length=16)),
                ('browser_family', models.CharField(blank=True, max_length=64)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='experiments.experiment')),
            ],
            options={
                'ordering': ('-started_at',),
            },
        ),
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_value', models.TextField(help_text='JSON-encoded answer payload (int, str, or list depending on question type).')),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='experiments.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.participantsession')),
                ('stimulus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='experiments.stimulus')),
            ],
            options={
                'ordering': ('session', 'answered_at'),
            },
        ),
        migrations.CreateModel(
            name='StimulusAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.PositiveIntegerField()),
                ('started_listening_at', models.DateTimeField(blank=True, null=True)),
                ('listen_duration_ms', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='survey.participantsession')),
                ('stimulus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='experiments.stimulus')),
            ],
            options={
                'ordering': ('session', 'sort_order'),
                'unique_together': {('session', 'sort_order')},
            },
        ),
    ]
