# Generated by Django 5.2.13 on 2026-04-11 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsession',
            name='current_assignment_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='current_page_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='participantsession',
            name='demographic_page_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
