# Generated by Django 5.2.13 on 2026-04-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiments', '0003_experiment_instructions_content_experiment_mode_and_more'),
        ('survey', '0002_participantsession_current_assignment_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='participantsession',
            name='current_pair_index',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='PairAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_group', models.CharField(max_length=200)),
                ('position_a', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], help_text='Which side stimulus A appears on (left or right).', max_length=5)),
                ('sort_order', models.PositiveIntegerField()),
                ('listen_duration_a_ms', models.PositiveIntegerField(default=0)),
                ('listen_duration_b_ms', models.PositiveIntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_assignments', to='survey.participantsession')),
                ('stimulus_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_assignments_as_a', to='experiments.stimulus')),
                ('stimulus_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pair_assignments_as_b', to='experiments.stimulus')),
            ],
            options={
                'ordering': ('session', 'sort_order'),
                'unique_together': {('session', 'sort_order')},
            },
        ),
        migrations.AddField(
            model_name='response',
            name='pair_assignment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='survey.pairassignment'),
        ),
    ]
