# Generated by Django 5.2.13 on 2026-04-15 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0003_participantsession_current_pair_index_pairassignment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participantsession',
            name='last_step',
            field=models.CharField(choices=[('consent', 'Consent'), ('instructions', 'Instructions'), ('audio_check', 'Audio playback check'), ('stimuli', 'Listening to stimuli'), ('demographics', 'Demographic questions'), ('done', 'Completed')], default='consent', max_length=16),
        ),
    ]
