# Generated by Django 5.2.13 on 2026-04-22 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_alter_participantsession_last_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='pairassignment',
            name='listen_duration_prompt_ms',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
