# Generated by Django 5.2.13 on 2026-06-02 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0005_pairassignment_listen_duration_prompt_ms"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="resume_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
    ]
