# Generated by Django 5.2.13 on 2026-06-02 08:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("experiments", "0015_experiment_eligibility_rule_alter_question_section"),
        ("survey", "0007_participantsession_screened_out_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="assigned_condition",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="experiments.condition",
            ),
        ),
    ]
