# Generated by Django 5.2.13 on 2026-06-02 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0008_participantsession_assigned_condition"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="failed_attention_checks",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="participantsession",
            name="flags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
