# Generated by Django 5.2.13 on 2026-06-02 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0009_participantsession_failed_attention_checks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="participant_uid",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
