# Generated by Django 5.2.13 on 2026-06-02 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0010_participantsession_participant_uid"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="compensation_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("paid", "Paid"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="participantsession",
            name="completion_code",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="participantsession",
            name="external_id",
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
    ]
