# Generated by Django 5.2.13 on 2026-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0011_participantsession_compensation_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="withdrawn_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="participantsession",
            name="last_step",
            field=models.CharField(
                choices=[
                    ("consent", "Consent"),
                    ("screening", "Screening / eligibility"),
                    ("instructions", "Instructions"),
                    ("audio_check", "Audio playback check"),
                    ("stimuli", "Listening to stimuli"),
                    ("demographics", "Demographic questions"),
                    ("screened_out", "Screened out (ineligible)"),
                    ("withdrawn", "Withdrawn"),
                    ("done", "Completed"),
                ],
                default="consent",
                max_length=16,
            ),
        ),
    ]
