# Generated by Django 5.2.13 on 2026-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0012_participantsession_withdrawn_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="is_preview",
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
