# Generated by Django 5.2.13 on 2026-06-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0013_participantsession_is_preview"),
    ]

    operations = [
        migrations.AddField(
            model_name="response",
            name="elapsed_ms",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
