# Generated by Django 5.2.13 on 2026-06-02 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0014_response_elapsed_ms"),
    ]

    operations = [
        migrations.CreateModel(
            name="SurveyEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("started", "Session started"),
                            ("page_submit", "Page submitted"),
                            ("screened_out", "Screened out"),
                            ("completed", "Completed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=64)),
                ("elapsed_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="survey.participantsession",
                    ),
                ),
            ],
            options={
                "ordering": ("session", "created_at", "id"),
                "indexes": [
                    models.Index(
                        fields=["session", "created_at"],
                        name="survey_surv_session_b3d9f3_idx",
                    )
                ],
            },
        ),
    ]
