# Generated by Django 5.2.13 on 2026-06-02 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("survey", "0015_surveyevent"),
    ]

    operations = [
        migrations.AddField(
            model_name="participantsession",
            name="consent_version",
            field=models.CharField(blank=True, max_length=16),
        ),
    ]
